export const TenantData = [
    {
      "id": 1,
      "property": "Property 1",
      "unit_id_or_name": "Unit 101",
      "first_name": "John",
      "last_name": "Doe",
      "phone_number": "+1234567890",
      "account_number": "123456789",
      "national_id": "1234567890",
      "email": "john.doe@example.com",
      "kra_tax_pin": "KRA123456",
      "rent_penalty_type": "fixed",
      "rent_penalty_amount": 50.0,
      "rent_penalty_percentage": null,
      "notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "move_in_date": "2023-01-01",
      "move_out_date": "2024-01-01",
      "other_phone_numbers": "+1987654321",
      "lease_start_date": "2023-01-01",
      "lease_expiry_date": "2024-01-01",
      "lease_notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "file_upload": "tenant_documents/john_doe_contract.pdf"
    },
    {
      "id": 2,
      "property": "Property 2",
      "unit_id_or_name": "Unit 202",
      "first_name": "Alice",
      "last_name": "Smith",
      "phone_number": "+9876543210",
      "account_number": "987654321",
      "national_id": "0987654321",
      "email": "alice.smith@example.com",
      "kra_tax_pin": "KRA987654",
      "rent_penalty_type": "percentage",
      "rent_penalty_amount": null,
      "rent_penalty_percentage": 5.0,
      "notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "move_in_date": "2023-02-01",
      "move_out_date": "2024-02-01",
      "other_phone_numbers": "+1122334455",
      "lease_start_date": "2023-02-01",
      "lease_expiry_date": "2024-02-01",
      "lease_notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "file_upload": "tenant_documents/alice_smith_contract.pdf"
    },
    // Add more samples as needed...
    {
        "id": 3,
        "property": "Property 3",
        "unit_id_or_name": "Unit 303",
        "first_name": "Emma",
        "last_name": "Johnson",
        "phone_number": "+1122334455",
        "account_number": "112233445",
        "national_id": "1122334455",
        "email": "emma.johnson@example.com",
        "kra_tax_pin": "KRA112233",
        "rent_penalty_type": "fixed",
        "rent_penalty_amount": 100.0,
        "rent_penalty_percentage": null,
        "notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "move_in_date": "2023-03-01",
        "move_out_date": "2024-03-01",
        "other_phone_numbers": "+9988776655",
        "lease_start_date": "2023-03-01",
        "lease_expiry_date": "2024-03-01",
        "lease_notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "file_upload": "tenant_documents/emma_johnson_contract.pdf"
    },
    {
        "id": 4,
        "property": "Property 4",
        "unit_id_or_name": "Unit 404",
        "first_name": "Michael",
        "last_name": "Brown",
        "phone_number": "+3344556677",
        "account_number": "334455667",
        "national_id": "3344556677",
        "email": "michael.brown@example.com",
        "kra_tax_pin": "KRA334455",
        "rent_penalty_type": "percentage",
        "rent_penalty_amount": null,
        "rent_penalty_percentage": 3.5,
        "notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "move_in_date": "2023-04-01",
        "move_out_date": "2024-04-01",
        "other_phone_numbers": "+1122334455",
        "lease_start_date": "2023-04-01",
        "lease_expiry_date": "2024-04-01",
        "lease_notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "file_upload": "tenant_documents/michael_brown_contract.pdf"
    },
    {
        "id": 5,
        "property": "Property 5",
        "unit_id_or_name": "Unit 505",
        "first_name": "Sophia",
        "last_name": "Miller",
        "phone_number": "+5566778899",
        "account_number": "556677889",
        "national_id": "5566778899",
        "email": "sophia.miller@example.com",
        "kra_tax_pin": "KRA556677",
        "rent_penalty_type": null,
        "rent_penalty_amount": null,
        "rent_penalty_percentage": null,
        "notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "move_in_date": "2023-05-01",
        "move_out_date": "2024-05-01",
        "other_phone_numbers": "+3344556677",
        "lease_start_date": "2023-05-01",
        "lease_expiry_date": "2024-05-01",
        "lease_notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "file_upload": "tenant_documents/sophia_miller_contract.pdf"
    },
    {
        "id": 6,
        "property": "Property 6",
        "unit_id_or_name": "Unit 606",
        "first_name": "James",
        "last_name": "Taylor",
        "phone_number": "+7788990011",
        "account_number": "778899001",
        "national_id": "7788990011",
        "email": "james.taylor@example.com",
        "kra_tax_pin": "KRA778899",
        "rent_penalty_type": null,
        "rent_penalty_amount": null,
        "rent_penalty_percentage": null,
        "notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "move_in_date": "2023-06-01",
        "move_out_date": "2024-06-01",
        "other_phone_numbers": "+5566778899",
        "lease_start_date": "2023-06-01",
        "lease_expiry_date": "2024-06-01",
        "lease_notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "file_upload": "tenant_documents/james_taylor_contract.pdf"
    },
    {
        "id": 7,
        "property": "Property 7",
        "unit_id_or_name": "Unit 707",
        "first_name": "Olivia",
        "last_name": "Anderson",
        "phone_number": "+1122334455",
        "account_number": "112233445",
        "national_id": "1122334455",
        "email": "olivia.anderson@example.com",
        "kra_tax_pin": "KRA112233",
        "rent_penalty_type": "fixed",
        "rent_penalty_amount": 150.0,
        "rent_penalty_percentage": null,
        "notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "move_in_date": "2023-07-01",
        "move_out_date": "2024-07-01",
        "other_phone_numbers": "+9988776655",
        "lease_start_date": "2023-07-01",
        "lease_expiry_date": "2024-07-01",
        "lease_notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "file_upload": "tenant_documents/olivia_anderson_contract.pdf"
    },
    {
        "id": 8,
        "property": "Property 8",
        "unit_id_or_name": "Unit 808",
        "first_name": "William",
        "last_name": "Martinez",
        "phone_number": "+3344556677",
        "account_number": "334455667",
        "national_id": "3344556677",
        "email": "william.martinez@example.com",
        "kra_tax_pin": "KRA334455",
        "rent_penalty_type": "percentage",
        "rent_penalty_amount": null,
        "rent_penalty_percentage": 4.5,
        "notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "move_in_date": "2023-08-01",
        "move_out_date": "2024-08-01",
        "other_phone_numbers": "+1122334455",
        "lease_start_date": "2023-08-01",
        "lease_expiry_date": "2024-08-01",
        "lease_notes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "file_upload": "tenant_documents/william_martinez_contract.pdf"
    }
];
